---
# tasks file for rhel-patching-tasks
- name: Continue with processing ?
  pause:
    prompt: Please confirm you want to continue. Press return to continue. Press Ctrl+c and then "a" to abort
  when: a is defined

## you can use OS specific modules like dnf or apt with os distribution checks
## Also can filter packages related to security or
- name: Updating all packages on Host
  yum:
    name: '*'
    state: latest
    exclude: 'ImageMagick*'
    update_cache: yes
    update_only: no
  register: package_update_status
  #when: dopatch is defined

- name: Package Upadte Status
  debug:
    msg: "{{ package_update_status }}"
  #when: dopatch is defined

- name: Comparing last updated kernel and running kernel
  shell: |
    LAST_KERNEL=$(rpm -q --last kernel |head -1 | awk '{print $1}' | sed 's/kernel-//');
    CURRENT_KERNEL=$(uname -r)

    if [[ $LAST_KERNEL != $CURRENT_KERNEL ]]; then
      # Set reboot flag
      touch /tmp/reboot
      echo "KERNEL_CHANGED"
    else
      echo "No KERNEL Change Detected"
    fi
  register: kernel_update_status

- name: Reboot Requirement
  debug:
    msg: "{{ kernel_update_status.stdout }}"


# Shutdown/stop any services before reboot if needed
- name: Pre-Reboot Scripts
  debug:
    msg: "Running Pre-Reboot scripts............."

- name: Reboot the machine (Wait for 2 min or 120 Sec)
  reboot:
    reboot_timeout: 120
    test_command: uptime
  when: package_update_status.changed or kernel_update_status.stdout == "KERNEL_CHANGED"
  register: reboot_status

- name: Machine after reboot
  debug:
    msg: "{{ reboot_status }}"
